# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd6890906cf8566d9ca8cb4971c8bc353f74ef119d22c50518879162cf5ad77c8db77d78ecbbd18f1d029ebd2486b01bcd6ea7c1786d6acb77e87666a4114d59

test:
  secret_key_base: 91fe88639da1c11bd83dedbc9971d12d2850eff3a088ab62fd84acc4770bd5c80e6675589835d403b1548e202b159e5b47827af1f9c589c792012c7bf5609ff0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
